### ISSUE TITLE
GTK libraries

### ISSUE THREAD

**Issue by waltbrainerd** [vmagnin/gtk-fortran#100]
Still working on Windows 10.

pkg-config gives me the following required GTK libraries:

 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl

If I refer (-L) to the MSYS2 distribution, things work.
If I move the listed libraries to another location, many things appear to be missing.
How can I tell what else is needed?

Thanks.

**Comment by vmagnin** [comment]
I close this old issue but you can reopen it if you have the same problem or a solution.
