### ISSUE TITLE
Is Doxygen used in gtk-fortran ?

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/gtk-fortran#120]
It seems that Doxygen support was added in gtk-fortran a long time ago (2011) but is perhaps not used. From what I understand here (https://modelingguru.nasa.gov/docs/DOC-1811), in Fortran a Doxygen directive seems to be introduced by `!>` and I do not find any in the project. But I am not familiar with Doxygen:

1) Do you know if Doxygen is used somewhere in gtk-fortran ?
2) Should we use it ?
3) Or should we delete it from the CMake files ?
4) Or should we keep it even if not used ? (does gtk-fortran build if Doxygen is not installed ?)

**Comment by vmagnin** [comment]
I tried to uninstall Doxygen, but it prevents building gtk-fortran:
```
gtk-fortran/build$ cmake ..                                         
-- Compiler: GNU 7.2.0 /usr/bin/f95                                                                                         
-- Build type is: release                                                                                                   
-- Compilation flags: -pthread -O3 -mtune=native -march=native                                                              
CMake Warning at /usr/share/cmake-3.9/Modules/FindDoxygen.cmake:396 (message):                                              
  Unable to determine doxygen version: No such file or directory                                                            
Call Stack (most recent call first):                                                                                        
  /usr/share/cmake-3.9/Modules/FindDoxygen.cmake:551 (_Doxygen_find_doxygen)                                                
  CMakeLists.txt:130 (find_package)                                                                                         
                                                                                                                           
                                                                                                                           
-- Found Doxygen: /usr/bin/doxygen  found components:  doxygen dot 
CMake Error at /usr/share/cmake-3.9/Modules/FindDoxygen.cmake:630 (message):
  Unable to generate Doxyfile template: No such file or directory
Call Stack (most recent call first):
  CMakeLists.txt:130 (find_package)

-- Configuring incomplete, errors occurred!
See also
```

**Comment by vmagnin** [comment]
CMakeLists.txt has been modified in master and gtk3 branches: CMake will use Doxygen only if the package is found.

By now, Doxygen is not used in any file but it could be used in the future.

**Comment by vmagnin** [comment]
Doxygen dependence is removed from the gtk3 branch, because it was never used in the project.

**Comment by band-a-prend** [comment]
Doxygen wasn't used directly in gtk-fortran. But it (with graphviz for diagrams for call graph) is useful to build developer documentation. 

Such doxygen documentation successfully built for latest relase gtk-fortran v19.04.gtk3.24.8.

It seems that doxygen documentation blocks starts just with `!` before description of functions and subroutines or even just on the base of definition.
