### ISSUE TITLE
Kind mismatch in source (bug)

### ISSUE THREAD

**Issue by waltbrainerd** [vmagnin/gtk-fortran#123]
The type/kind passed to g_value_init in gtk-hl-tree.f90 is integer(type_kind)
and type_kind is c_long.

The 2nd dummy argument to that function is integer(c_size_t).

I think I reported this a couple of years ago (or something like it).

c_size_t and c_long are not necessarily the same (they are not on gfortran/Windows).

$ cat f.f90
use, intrinsic :: iso_c_binding
print *, c_size_t, c_long
end

Walt@HP_Envy /cygdrive/c/walt/FortranTools70/Src/GTK/GTK_Fortran/Src
$ gfortran f.f90

Walt@HP_Envy /cygdrive/c/walt/FortranTools70/Src/GTK/GTK_Fortran/Src
$ ./a
           8           4
============
In case anybody is interested, I have a Makefile that builds what I call libgtkfortran.a on Windows.
[I am not able to get any of the scripts or cmake in the distribution to work.]

**Comment by vmagnin** [comment]
Hi Walt,
it is true that your fix proposed for issue https://github.com/vmagnin/gtk-fortran/issues/99 was not committed ! Now, it's done in master and gtk3 branches.

Concerning the Makefile that builds libgtkfortran.a on Windows, I think we could include it in the gtk-fortran repository. I guess you can do it using the _Pull request_ function in github.
