### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by bsbhro** [vmagnin/gtk-fortran#148]
All plplot examples built, but they all give this message (...17e is one ex.)
[plplot (gtk3)]$ ./hl_plplot17e
./hl_plplot17e: symbol lookup error: ./hl_plplot17e: undefined symbol: __plplot_MOD_plparseopts_brief

**Comment by vmagnin** [comment]
> All plplot examples built, but they all give this message (...17e is one ex.)
> [plplot (gtk3)]$ ./hl_plplot17e
> ./hl_plplot17e: symbol lookup error: ./hl_plplot17e: undefined symbol: __plplot_MOD_plparseopts_brief

@bsbhro,
it seems the PLplot fortran module directory is not found.

Can you give me some information on your system: Linux distribution, compiler, PLplot version (you now need >=5.13), etc. Also, have you installed PLplot as a package or from source using CMake ? Can you paste the information printed by the ` cmake -D CMAKE_BUILD_TYPE=debug ..` command ?

The latest gtk3 branch now uses pkg-config to find PLplot directories. If you know where are the pkgconfig files of PLplot you can try something like:
`PKG_CONFIG_PATH=/home/osboxes/myplplot/lib/pkgconfig cmake -D CMAKE_BUILD_TYPE=debug ..`

**Comment by bsbhro** [comment]
Thank you for your prompt reply. your questions were the occasion to try it on another notebook with xubuntu 18.10. I installed the plplot 5.13 with apt, then the gtk-fortran. gcc 8.2 built without stop and all 41 tests worked immediately. How cool is that!
On the PC with the error I have kernel 5, gcc 8.3, plplot 5.14 from source. It may be that there is a confusion.
thanks for the great work!

**Comment by vmagnin** [comment]
> Thank you for your prompt reply. your questions were the occasion to try it on another notebook with xubuntu 18.10. I installed the plplot 5.13 with apt, then the gtk-fortran. gcc 8.2 built without stop and all 41 tests worked immediately. How cool is that!

Fine ! 

> On the PC with the error I have kernel 5, gcc 8.3, plplot 5.14 from source. It may be that there is a confusion.

I have tested the project on a Debian Sid where I have built PLplot 5.14 from source. The exact command I used for preparing the gtk-fortran building is:

`PKG_CONFIG_PATH=/home/osboxes/myplplot/lib/pkgconfig cmake -D CMAKE_BUILD_TYPE=debug -D CMAKE_PREFIX_PATH=/home/osboxes/myplplot ..`

where `/home/osboxes/myplplot` is the directory where I have installed PLplot 5.14.
Tell me if that works for you.

> thanks for the great work!

Thanks !

**Comment by bsbhro** [comment]
Hi, Good Morning,
on my 'first' box (xubuntu18.10, gfortran 8.3, gtk-3, ...) the hl_plplot* examples are newly built and working like expected (how cool is the strip chart demo :-). I purged the plplot-package, I removed all plplot* files in /usr and installed PLplot 5.14 from plplot.git .
Thank you very much, have a nice Sunday! Dear greetings from Germany.

**Comment by vmagnin** [comment]
> Hi, Good Morning,
> on my 'first' box (xubuntu18.10, gfortran 8.3, gtk-3, ...) the hl_plplot* examples are newly built and working like expected (how cool is the strip chart demo :-). I purged the plplot-package, I removed all plplot* files in /usr and installed PLplot 5.14 from plplot.git .
> Thank you very much, have a nice Sunday! Dear greetings from Germany.

You're welcome, greetings from France !
