### ISSUE TITLE
Migration from CMake to Meson ?

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/gtk-fortran#155]
In CMake, there is a FindGTK2 module that is used by gtk-fortran:
https://cmake.org/cmake/help/v3.12/module/FindGTK2.html

For GTK 3, we use the following FindGTK3.cmake file:
https://github.com/vmagnin/gtk-fortran/blob/gtk3/cmake/FindGTK3.cmake
which probably comes from another project like https://github.com/eiskaltdcpp/eiskaltdcpp

This post tells that GNOME people don't use CMake and don't provide to the CMake project the files for finding GTK with CMake:
http://cmake.3232098.n2.nabble.com/How-to-find-GTK3-in-CMake-td7598675.html

So, to find GTK 4, we will probably have to adapt that file or to find one in another project (with a compatible license).

**Comment by bonanza** [comment]
I suggest to migrate the build system to [Meson](https://mesonbuild.com/index.html). [This](https://meghprkh.github.io/blog/2016/07/11/Adventures-with-the-Meson-Build-System-and-a-GTK-Playground/) sounds very promising.

**Comment by vmagnin** [comment]
> I suggest to migrate the build system to [Meson](https://mesonbuild.com/index.html).

Hi Jens,

if it used by the GTK people, it can make sense. 

CMake is a huge piece of software and is difficult to master. With the new PLplot versions, I have not yet succeeded to build the gtk-fortran PLplot examples following the CMake logic, but I was obliged to use the pkg-config CMake module.

Note that in the current gtk-fortran, CMake is building everything OK (gtk-fortran, gtk-hl, PLplot examples, sketcher) under all platforms where I tested it: Linux, FreeBSD, Windows (MSYS2). And in parallel mode.

But we could add Meson build files in the project, as an experimental feature. Perhaps the biggest problem would be with the PLplot part because PLplot is based on CMake. But if Meson can use pkg-config it should be OK.

And of course, we would have to test it under all main platforms.

**Comment by vmagnin** [comment]
https://mesonbuild.com/Release-notes-for-0-49-0.html
```
CMake find_package dependency backend
Meson can now use the CMake find_package ecosystem to detect dependencies. 
```

**Comment by liberforce** [comment]
The FindGTKx files are note appropriate. They usually are outdated or incomplete (AFAIR, the GTK 3 only handles one single platform). For CMake, the finder based on pkg-config is what should be used, if you want to stick to CMake. Otherwise, yes, Meson is probably the way to go.

**Comment by vmagnin** [comment]
> The FindGTKx files are note appropriate. They usually are outdated or incomplete (AFAIR, the GTK 3 only handles one single platform). For CMake, the finder based on pkg-config is what should be used, if you want to stick to CMake. Otherwise, yes, Meson is probably the way to go.

Thank you for your post.
I have just cloned your https://github.com/liberforce/gtk-samples repository and build the examples. It is interesting to see that meson & ninja are used just the same as cmake & make:
```bash
$ mkdir build && cd build
$ meson ..
$ ninja
```
and that telling meson to use GTK 3 is as simple as writting in the meson.build file:
```meson
deps = [
    dependency('gtk+-3.0')
]
```

**Comment by vmagnin** [comment]
The Meson build system provides a script to help converting CMake files to Meson files: 
https://mesonbuild.com/Build-system-converters.html

Update: that script is not really helpful... I will work from scratch.

**Comment by vmagnin** [comment]
I have started working with the Meson build system. But there is a bug in the 0.49.0 version: it can not build Fortran files containing several modules.
It was fixed in the development branch (0.50.999): https://github.com/mesonbuild/meson/pull/4979
So, Meson >= 0.51 will be needed.

**Comment by vmagnin** [comment]
Experimental `meson.build` files have been added. Meson>=0.51 is needed. Commands are `meson buildmeson` and `ninja -C buildmeson`. You can install the library using `sudo ninja -C buildmeson install`, but there is still some problems for installing the `.mod` files (see https://github.com/mesonbuild/meson/issues/5374).

**Comment by vmagnin** [comment]
Concerning CMake, I have removed the cmake/FindGTK3.cmake module. 
We are now using the same commands that were already used for MSYS2:

```cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(GTK REQUIRED ${GTKname})
# Setup CMake to use GTK, tell the compiler where to look for headers
# and to the linker where to look for libraries:
include_directories(${GTK_INCLUDE_DIRS})
link_directories(${GTK_LIBRARY_DIRS})
# Add other flags to the compiler:
add_definitions(${GTK_CFLAGS_OTHER})
```

In GTK 4, we will replace `set(GTKname "gtk+-3.0")` by `set(GTKname "gtk4")`

**Comment by vmagnin** [comment]
CMake can now extract the GTK version from the VERSIONS file at the top of the project (it is generated by cfwrapper.py). It is ready for working with GTK 4 (tested under Fedora 31 with GTK 3.96).

A lot of cleanup has been made in the project. The remaining work for GTK 4 will mainly be to adapt all the examples and the High Level sublibrary to the changes made in GTK 4.
