### ISSUE TITLE
Bump CMake minimum required version to at least 3.4

### ISSUE THREAD

**Issue by zbeekman** [vmagnin/gtk-fortran#158]
**Describe the bug**

CMake 2.8 is ancient, and by setting the minimum required cmake version to 2.8.x CMake policies default to their OLD version even when newer CMake's are being used. You should upgrade to 3.4 at least.

**To Reproduce**

Build with `-Wdev` passed to CMake. On macOS this warns about CMP0042, which should be set to NEW when present (CMake 3.x and newer)

**Expected behavior**

Ancient build systems should be deprecated, and saner defaults provided by newer CMakes should be utilized

**Screenshots**
N/A

**Your system:**
 - OS version: MacOS 10.14 (Mojave)
 - Compiler version: GFortran 8.3 (brewed)

**Additional context**

**Comment by vmagnin** [comment]
@zbeekman 
I have modified the main `CMakeLists.txt` file in the current gtk3 and master (gtk2) branches:
```
cmake_minimum_required(VERSION 3.4)
```

But I have not modified the file `cmake/FindGTK3.cmake` which has on line 410:
```
cmake_minimum_required(VERSION 2.6.2)
```

I do not know if I should/can.

**Comment by zbeekman** [comment]
I think you can safely delete that line from FindGTK3.cmake.

**Comment by vmagnin** [comment]
> I think you can safely delete that line from FindGTK3.cmake.

It's done.
