### ISSUE TITLE
gtk.f90 file not found when compiling examples

### ISSUE THREAD

**Issue by benreu** [vmagnin/gtk-fortran#159]
**Describe the bug**
When I try to compile any example in the /examples directory I get the error: 
_gfortran: error: gtk.f90: No such file or directory_

**To Reproduce**
1. cd to the examples directory
2. run the command _gfortran gtk.f90 gtkzero.f90 -o gtkzero `pkg-config --cflags --libs gtk-3-fortran`_

Leaving off the gtk.g90 compiles without a hitch:
_gfortran gtkzero.f90 -o gtkzero `pkg-config --cflags --libs gtk-3-fortran`_

 - OS version: [e.g. Mint 19 64 bits]
 - Compiler version [e.g. gfortran 7.3.0]

**Comment by vmagnin** [comment]
The `gtk.f90` file (and the `*-auto.f90` files) is in the `src/` directory of the project and is part of the gkt-fortran library. So you should type:

    ~/gtk-fortran/examples$ gfortran -I../src ../src/glib-auto.f90 ../src/gtk.f90 gtkzero.f90 `pkg-config --cflags --libs gtk+-3.0`

or if you have already installed the gtk-3-fortran library (`sudo make install`):

    ~/gtk-fortran/examples$ gfortran gtkzero.f90 -o gtkzero `pkg-config --cflags --libs gtk-3-fortran`

Note that if you use such compiling commands and that you later want to use cmake and make instead, you will have to remove the `*.mod` files generated in the `src/` and `examples/` directories, to avoid make errors.

**Comment by benreu** [comment]
Could I suggest you update the examples with this info? Would you accept a pull request if I did so?

**Comment by vmagnin** [comment]
> Could I suggest you update the examples with this info? Would you accept a pull request if I did so?

@benreu 
Yes, it will help. 

Personally, I don't use anymore these compilation commands and prefer to use CMake / make (that is the reason why the comments in the headers of the examples are not always updated). But it can be useful for people who don't want to install CMake.

Note that for the \`pkg-config --cflags --libs gtk+-3.0\` form, the `*-auto.f90` files needed for compiling depend on each example.
