### ISSUE TITLE
gio_test

### ISSUE THREAD

**Issue by bsbhro** [vmagnin/gtk-fortran#160]
Hi, I compiled all files well with gfortran-9 and Ubuntu 19.04. If someone runs ctest in the build dir,
the gio_demo doesn't show the prompt 'Text >' and nobody knows the input termination
with ctrl-d. If one knows that, the next test goes further, with ctrl-c ends the test sequence.
![gio_test](https://user-images.githubusercontent.com/45314496/57967425-0983d700-795f-11e9-9870-759d0222a58f.png)

**Comment by vmagnin** [comment]
Hi @bsbhro 

Yes, same problem:

```bash
$ ctest -I 34
Test project gtk-fortran/build
    Start 34: gio_demo
Strange...
I don't know
1/8 Test #34: gio_demo .........................   Passed   17.23 sec
    Start 35: tests
2/8 Test #35: tests ............................   Passed    0.09 sec
    Start 36: hl_plplot8e
^C
$
```
Tested with Kubuntu 19.04, gfortran 9.0.1  and 8.3.0.

In fact, there is many examples that use `print *` or `write()` instructions to print some messages in the terminal, but `ctest` does not show those messages. I do not know if it's possible to force `ctest` to show them. I tried several options without success.

**Comment by bsbhro** [comment]
Hi, good morning,
when in build dir I call examples/gio_demo it works with prompt. Another possibility with prompt is 'xterm -e examples/gio_demo'. But I don't know how to modify the line 40 in CTestTestfile.cmake to execute xterm. Sure you know how add_test() works.

Another thing: 'cmake ..' brings the harmless (?) message 'missing: GTK3_GDKCONFIG_INCLUDE_DIR'. I modified line 477 in '../cmake/FindGTK3.cmake' to 'gdk/gdkconfig.h'. Then we have 'Found GTK3_GTK'. I like it more :-)

Ciao

**Comment by vmagnin** [comment]
Hi @bsbhro 

thanks for fixing the GDKCONFIG issue: I have updated and pushed `../cmake/FindGTK3.cmake`, the Wiki and the INSTALL file.

Concerning `ctest`, I am not the main contributor of the CMake parts of the project. So we will have to investigate how it works... By now, there is the line 76 `add_test(${example} ./${example})` in `examples/CMakeLists.txt`.

From the manual page:
https://cmake.org/cmake/help/v3.13/command/add_test.html#command:add_test
I guess that we could write something like `add_test(${example} xterm -e ./${example})`

Ciao

**Comment by bsbhro** [comment]
Hello, for Debian/Ubuntu I can say that xterm is part of any installation, even a minimal. Yes, this question I asked myself. Windows doesn't have an xterm. BSD and MacOS do have it, but if installed don't know. May be, this failure only affects bash on Ubuntu. Like you said it's strange :-)

**Comment by vmagnin** [comment]
The solution to see the output of each example is to use the ctest -V option (`--verbose`). In fact, it works fine except with gio_demo! (the "Text> " prompts appear only after you have type your inputs and CTRL+D to stop gio_demo):

```bash
$ ctest -V -I 34
UpdateCTestConfiguration  from :gtk-fortran/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :gtk-fortran/build/DartConfiguration.tcl
Test project gtk-fortran/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 34
    Start 34: gio_demo

34: Test command: gtk-fortran/build/examples/gio_demo
34: Test timeout computed to be: 10000000
bla
bla
bla
34: Text> Text> Text> Text> 
1/8 Test #34: gio_demo .........................   Passed   13.13 sec
test 35
    Start 35: tests

35: Test command: gtk-fortran/build/examples/tests
35: Test timeout computed to be: 10000000
35:  test_iso_c_binding()
35:  test_c_char_in_out()
35:  test_guchar_in_out()
35:  test_gdouble_in_out()
35:  test_gulong_in()
35:  test_int16_in_out()
35:  test_uint16_in_out()
35:  test_int32_in_out()
35:  test_uint32_in_out()
35:  test_gboolean_in_out()
35:            1           1
35:            0           0
35: 
35:  No error
2/8 Test #35: tests ............................   Passed    0.06 sec
```
