### ISSUE TITLE
Replace gtk_container_set_border_width()

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/gtk-fortran#164]
https://developer.gnome.org/gtk4/3.98/ch31s02.html#id-1.6.4.4.23
> Stop using GtkContainer::border-width
> GTK 4 has removed the “border-width” property. Use other means to influence the spacing of your containers, such as the CSS margin and padding properties on child widgets. 

See :
https://github.com/vmagnin/gtk-fortran/blob/gtk3/examples/gtkhello.f90
https://developer.gnome.org/gtk4/stable/GtkWidget.html#GtkWidget--margin

Must be applied to the container, not the window!

**Comment by vmagnin** [comment]
```
src/gtk-hl-container.f90:55:       & gtk_container_set_border_width, gtk_label_new, &
src/gtk-hl-container.f90:153:    if (present(border)) call gtk_container_set_border_width(win, border)
src/gtk-hl-assistant.f90:52:       & gtk_assistant_set_page_type, gtk_container_set_border_width, &
src/gtk-hl-assistant.f90:119:    if (present(border)) call gtk_container_set_border_width(asstnt, border)

```

**Comment by vmagnin** [comment]
Replaced by gtk_widget_set_margin_start, gtk_widget_set_margin_end, gtk_widget_set_margin_top, gtk_widget_set_margin_bottom

**Comment by jerryd** [comment]
Good find.
