### ISSUE TITLE
Glade 3 Compatibility?

### ISSUE THREAD

**Issue by han190** [vmagnin/gtk-fortran#180]
Hi, first of all thanks for all the work towards Gtk4!

Well, the issue/request here is may be you could add some supports on Glade 3. I changed the version in `gtkbuilder.glade` to 3 and compiled `gtkbuilder2.f90`, but running `a.out` give me the following:
```
(a.out:49353): Gtk-WARNING **: 00:08:43.724: Could not find signal handler 'destroy'.  Did you compile with -rdynamic?

(a.out:49353): Gtk-WARNING **: 00:08:43.724: Could not find signal handler 'delete_event'.  Did you compile with -rdynamic?

(a.out:49353): Gtk-WARNING **: 00:08:43.724: Could not find signal handler 'destroy'.  Did you compile with -rdynamic?

(a.out:49353): Gtk-WARNING **: 00:08:43.724: Could not find signal handler 'button2clicked'.  Did you compile with -rdynamic?

(a.out:49353): Gtk-WARNING **: 00:08:43.724: Could not find signal handler 'hello'.  Did you compile with -rdynamic?
```
So, either I messed up something or it's just the glade 3 having trouble finding the signal handler correctly.

**Comment by vmagnin** [comment]
Hi @han190 ,

See the issue https://github.com/vmagnin/gtk-fortran/issues/49 for information about `-rdynamic`.

Can you give me more information about your:
- operating system (Linux, MSYS2/Windows, MacOS...),
- compiler (gfortran ?),
- gtk-fortran branch (gtk3 ?)

In the code of the CMakeLists.txt, there is for gfortran under Linux:
```
    if (UNIX)
        set(CMAKE_EXE_LINKER_FLAGS "-rdynamic")
    endif()
```

**Comment by han190** [comment]
The flag is not auto added by cmake, but it works well with
```shell
gfortran -rdynamic gtkbuilder2.f90 $(pkg-config --cflags --libs gtk-3-fortran)
```
BTW,
* Operating system: Fedora 31
* Compiler: GNU Fortran (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
* gtk-fortran branch: gtk3

**Comment by bonanza** [comment]
Hi @han190 ,
the gtkbuilder.glade contains a GTK+ 2 interface because it was written in times when glade was not running stable with GTK+ 3. However, all the deprecated GTK+ 2 objects were removed and gtkbuilder.glade is running well with GTK+ 3. You can test it by opening the glade file with a current version of glade (I tested 3.22.1) and rewriting it (this writes the entry 
`<requires lib="gtk+" version="3.0"/>`).

**Comment by vmagnin** [comment]
@han190 , @bonanza 
strange that CMake does not detect that your configuration needs `-rdynamic`...
I will look in my Fedora 31 virtual machine when I have some time.

Concerning GTK 4, I have not yet created the gtk4 branch but the core of gtk-fortran (wrapper and building system) is now ready to move toward the next GTK major version. As  you can see in the Issues, there will be quite a lot of work to adapt the examples and the HL sub-library to the changes introduced in GTK 4 (I have made some tests with Manjaro 18.1.5 + GTK 3.98 and Fedora 31 + GTK 3.96). Of course, everybody which could help me in that task is welcome !

**Comment by vmagnin** [comment]
@han190 
I have tested under Fedora 32 (gfortran 10.0.1):
```
$ gfortran gtkbuilder2.f90 $(pkg-config --cflags --libs gtk-3-fortran --with-path=/usr/local/lib/pkgconfig/)
$ ./a.out
```
I have obtained the same warnings as you. And they disappear if I add `-rdynamic`.

But when building gtk-fortran with cmake, there is no problem with gtkbuilder2.f90. So cmake does take into account the `set(CMAKE_EXE_LINKER_FLAGS "-rdynamic")` instruction in CMakeLists.txt.

If I add `-rdynamic` in the `/usr/local/lib/pkgconfig/gtk-3-fortran.pc`:
```
Cflags: -rdynamic -I${includedir}
```
the warnings disappear when compiling directly `gtkbuilder2.f90`. So I guess I should commit that in gtk-fortran. But only in the UNIX case...

**Comment by vmagnin** [comment]
@han190 
I have committed the fix. Tested under Ubuntu 19.10, Lubuntu 20.04 and Fedora 32. I will also test with MSYS2/Windows 7 which is not identified as a UNIX by CMake.

And I have opened a new issue https://github.com/vmagnin/gtk-fortran/issues/185 about the pkg-config path problem under Fedora. Have you the same problem ?

**Comment by vmagnin** [comment]
Tested with FreeBSD 12.1 64bits.
