### ISSUE TITLE
Connection to Slack

### ISSUE THREAD

**Issue by jerryd** [vmagnin/gtk-fortran#181]
I have been using slack and can send you a link to enable the connection from slack to gtk-fortran if OK with you.

**Comment by vmagnin** [comment]
Hi @jerryd 
I hope everything is OK for you.
I am not familiar with slack. Can you explain what would be the added value ?

**Comment by jerryd** [comment]
Hi,
Just now saw this. I am not well versed in using Slack at all. I know a lot of people who do. One thing it is useful for is it maintains live chat capability with team members and notifications from github.  If there is a way to do this without using slack, thats OK with me too. In particular I wanted to dialogue with you about a pet project I have. Purely unfunded, personal learning thing.

I use a code called nec2c which is used to model fields around antennas. I discovered it uses gtk, so I thought about porting this over to gfortran-gtk and then use more advance fortran features, such as coarrays to parallel compute the solutions.  The original code was Fortran, then this was ported to C for whatever reason.  I thought it a perfect use of gfortran-gtk.  It is not a huge code base so I think its doable.

**Comment by vmagnin** [comment]
Hi Jerry,
I will send you an e-mail on your @c*.net address. I don't think GitHub has tools for private messages or chatting.
