### ISSUE TITLE
relocation against `hl_gtk_assistant_destroy' in read-only section `.rodata'

### ISSUE THREAD

**Issue by band-a-prend** [vmagnin/gtk-fortran#183]
**Describe the bug**
During compilation with `-DNO_BUILD_HL=false` the `warning: relocation against `hl_gtk_assistant_destroy' in read-only section `.rodata'` and the `warnings: creating a DT_TEXTREL in object` appear on the linking phase.

> Text relocations force the dynamic linker to perform extra work at startup, 
> waste system resources, and may pose a security risk.  
> On some architectures, the code may not even function properly, if at all.

**To Reproduce**
1. Compile gtk-fortran with `-DNO_BUILD_HL=false`
2. Notice the error on linking  (e.g. while build `gtkf-sketcher.f90.o`):
```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/gtk-fortran_object.dir/gtk-hl-assistant.f90.o: warning: relocation against `hl_gtk_assistant_destroy' in read-only section `.rodata'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: creating a DT_TEXTREL in object

```
and (while Linking Fortran executable gtkf-sketcher)
```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../src/libgtk-3-fortran.a(gtk-hl-chooser.f90.o): warning: relocation against `hl_gtk_chooser_resp_cb' in read-only section `.rodata'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: creating a DT_TEXTREL in object

```
This error isn't related to gtkf-sketcher itself but to `gtk-hl-chooser.f90.o` (hl_gtk_chooser_resp_cb)
and absent in build with  `-DNO_BUILD_HL=true`.

**Expected behavior**
Linking without warnings about `creating a DT_TEXTREL  in object`

**Your system:**
 - OS version: [e.g. Gentoo 64 bits]
 - Compiler version [e.g. gfortran 9.2.0]

**Comment by vmagnin** [comment]
Thanks @band-a-prend for reporting this issue,

I have found some clues:
https://gcc.gnu.org/legacy-ml/gcc-help/2006-11/msg00390.html
https://stackoverflow.com/questions/5311515/gcc-fpic-option/5311538#5311538

It seems we need somewhere the -fPIC option ("Generate position-independent code (PIC)") to create a shared library.

**Comment by band-a-prend** [comment]
I tried to add `-fPIC` to `CMakeLists.txt` block
```
    if (UNIX)
        set(CMAKE_EXE_LINKER_FLAGS "-rdynamic")
    endif()
```
additionally `-rdynamic` or instead it but without any success to build without mentioned warnings.

**Comment by vmagnin** [comment]
@band-a-prend 

With Ubuntu 19.10 64bits and gfortran 9.2.1, there is no warning.
Updated: no warning with Fedora 32 & gfortran 10.0.1.

**Comment by vmagnin** [comment]
The warning now appears in Fedora Rawhide with GTK 3.99.0 and gfortran 10.2.1:
```bash
[23%] Linking Fortran shared library libgtk-4-fortran.so
/usr/bin/ld: CMakeFiles/gtk-fortran_object.dir/gtk-hl-assistant.f90.o: warning: relocation against `hl_gtk_assistant_destroy' in read-only section `.rodata'
/usr/bin/ld: warning: creating DT_TEXTREL in a shared object
[ 23%] Built target gtk-fortran_shared
```

**Comment by vmagnin** [comment]
Still present in Fedora Rawhide (34) with GTK 3.99.5 and gfortran 11.0.0.

**Comment by vmagnin** [comment]
I now have a lot of those warnings in the gtk3 branch with gfortran 10.2.0 (Kubuntu 20.10).

**Comment by jtappin** [comment]
I think that adding the `--no-pie` option in the program build step gets rid of them. Can't remember where I found that, but it works for one of the event handlers in `graffer`.

**Comment by vmagnin** [comment]
Hi James @jtappin ,
thanks for the clue. I will try that option.

So PIE is "Position Independent Executable":
https://stackoverflow.com/questions/47778099/what-is-no-pie-used-for
https://stackoverflow.com/questions/49101265/how-to-configure-gcc-to-use-no-pie-by-default
It's for hardened security. So is it a good idea to remove it? Is there any solution to keep PIE but remove the warnings ?
