### ISSUE TITLE
GTK 4: a new menu example is needed

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/gtk-fortran#205]
`menu.f90` and `menu2.f90` were removed from the gtk4 branch because they were based on several deprecated APIs:
https://developer.gnome.org/gtk4/unstable/ch40s02.html#id-1.7.4.4.65
> Menus can already be replaced using GtkPopoverMenu in GTK 3. Additionally, GTK 4 introduces GtkPopoverMenuBar to replace menubars. These new widgets can only be constructed from menu models, so the porting effort involves switching to menu models and actions. 

See also issue https://github.com/vmagnin/gtk-fortran/issues/171

A new menu example should be written from scratch, based on the PopoverMenu API:

- https://developer.gnome.org/gtk4/stable/GtkPopoverMenu.html
- https://developer.gnome.org/gtk4/stable/GtkPopoverMenuBar.html

A new High Level gtk-hl-menu.f90 could be written to replace the version removed from gtk4 branch.

**Comment by jerryd** [comment]
Current status is I have some preliminaries of OOPish implementation of a general purpose application class and userinterface class, testing with gtk3 to get these sorted out as an infrastructure for any app, then will modify to gtk4

**Comment by vmagnin** [comment]
A new menubar.f90, contributed by @jerryd, demonstrates a menubar based on GMenu and GAction. It also uses CSS styles:
https://github.com/vmagnin/gtk-fortran/blob/gtk4/examples/menubar.f90

It is based on https://github.com/ToshioCP/Gtk4-tutorial/blob/main/src/menu/menu2.c
