### ISSUE TITLE
Packing more than one cell renderer in treeview column

### ISSUE THREAD

**Issue by konokadam** [vmagnin/gtk-fortran#226]
Hi,

First of all thank you very much for this great library. I'm playing with treeview widget for some time. You can check my github share https://github.com/konokadam/ForGtkAdvancedTreeviewInput. While trying to write codes for my desired treeviews I met some difficulties using gtk-fortran, that is gtk-hl-tree is very helpful generally, however it is not enough if you would like to pack more than one cell renderer in one treeview column. So I found solution by searching C and Python treeview examples or forums :)
During my trials I found that in gtk-hl-tree.f90, in subroutines (such as hl_gtk_list_tree_set_cell_data_func, etc) line: renderer = g_list_nth_data(rlist, 0_c_int) should have second argument as pack number of the cell renderer in treeview column. Here it has such an assumption that there is one cell renderer in one treeview column (so second argument had been given 0_c_int by default). 
Generally, I think it would be better if the difference of treestore (liststore) and treeview (listview) columns was more obvious in this hl-tree module.

Kind Regards,
Emrah

**Comment by vmagnin** [comment]
Hi @konokadam
welcome in our gtk-fortran small community!
I will clone and try your project as soon as possible. The screenshots are cool!

Feel free to work on gtk-hl-tree.f90 and make a pull request! The original author of the HL library is not maintaining it anymore, and it was a hard work for me to adapt it to GTK 4.0. Concerning gtk-hl-tree.f90, there is happily only 5 diff lines between the gtk3 and the gtk4 branches...

If you are interested, I can send you an invitation to our gfortran Slack which has a #gtk-fortran channel.

**Comment by konokadam** [comment]
Thank you @vmagnin , I would be happy if you add me to the #gtk-fortran channel.
I'm wo

**Comment by konokadam** [comment]
Thank you @vmagnin , I would be happy if you add me to the #gtk-fortran channel.
I'm working on treeview widget as I said, I would like to contribute the hl module if I can.

**Comment by vmagnin** [comment]
> Thank you @vmagnin , I would be happy if you add me to the #gtk-fortran channel.
> I'm working on treeview widget as I said, I would like to contribute the hl module if I can.

Hi @konokadam , you're welcome. I just need your email address to send you the Slack invitation. I did not find any usable email in the history of your git project. If you don't want to put it here, you can send me an email using one of my email address that you will find in the `$ git log` of gtk-fortran.

Can you also send me the command you use to compile and test your ForGtkAdvancedTreeviewInput project ?
