### ISSUE TITLE
GTK4 pkg-config name

### ISSUE THREAD

**Issue by han190** [vmagnin/gtk-fortran#227]
Hi, I read you post [here](https://fortran-lang.discourse.group/t/the-counter-intuitive-rise-of-python-in-scientific-computing/469/87) and tried your gtk4 branch. Everything goes smoothly and thank you for your effort!

A small issue is when link to a project we still use `gfortran xxx.f90 $(pkg-config --cflags --libs gtk-3-fortran)`, should it be renamed to `gtk-4-fortran`? (I know this branch isn't finalized yet, so ignore me if you are going to change it anyway!)

**Comment by vmagnin** [comment]
Hi @han190 ,
thank you for reporting everything is OK! I guess you used Fedora?
That's right, you must link to `gtk-4-fortran`, after of course having `sudo make install` it.
That naming allows to have gtk-3-fortran and gtk-4-fortran installed on the same machine (and even gtk-2-fortran).
I will update the doc later.

**Comment by han190** [comment]
Yes I am using Fedora 33 and yes I get the `gtk-4-fortran` option. Some of the mini apps I wrote before using `gtk-3-fortran` brokes, it's probably because gtk4 uses different function/widget names, I will have to go through their documentations.

**Comment by vmagnin** [comment]
Yes, many API were broken: some disappeared and were replaced by another API, the name or arguments of some functions changed...
- The official advices are here:
https://developer.gnome.org/gtk4/stable/gtk-migrating-3-to-4.html
- You can also look the GTK 4 issues in the gtk-fortran GitHub.
- Or look at the differences in the examples between the gtk3 and gtk4 branches:
`$ git diff gtk3 gtk4 -- gtkhello.f90`
- There is also some links toward interesting GTK 4 tutorials on this page:
https://github.com/vmagnin/gtk-fortran/wiki/Tutorials

**Comment by vmagnin** [comment]
I have written a new wiki page: https://github.com/vmagnin/gtk-fortran/wiki/Migrating-to-GTK-4
