### ISSUE TITLE
gtk-fortran should be usable as a dependency using the Fortran Package Manager (fpm)

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/gtk-fortran#229]
The new _Fortran Package Manager_ (fpm) can import dependencies from the web using git. For the moment it is limited to dependencies based on fpm. But in the future it should be able to import other projects which propose a build script, via the `build-script` variable of their fpm.toml file. Or even directly call CMake.

Our first attempt to use fpm is related here: https://github.com/fortran-lang/fpm/issues/351

See also: 
https://fortran-lang.discourse.group/t/google-summer-of-code-2021/658
https://github.com/fortran-lang/fortran-lang.org/wiki/GSoC-2021-Project-ideas

**Comment by Zaya6** [comment]
any progress on this?

**Comment by vmagnin** [comment]
The Fortran-lang community is working hard on fpm, but we must be patient. In order to use gtk-fortran as an fpm dependency, we need at least those two features:

- fpm must be able to manage CMake based projects: https://github.com/fortran-lang/fpm/issues/69
    - It is a part of the ideas proposed for the 2021 Google Summer of Code: https://github.com/fortran-lang/fortran-lang.org/wiki/GSoC-2021-Project-ideas#source-code-distribution-with-foreign-build-systems
 - fpm must be able to manage included files (`gtkenums-auto.f90` and `gtk-auto.f90`): https://github.com/fortran-lang/fpm/issues/358
 
Note that there is already many candidates for the GSoC 2021: https://fortran-lang.discourse.group/t/google-summer-of-code-2021/658/50
