### ISSUE TITLE
Interfaces to libcairo

### ISSUE THREAD

**Issue by ghost** [vmagnin/gtk-fortran#233]
This project contains interfaces to libcairo that would be useful to have available as a separate _fpm_ package. I could create such a package, with proper credit, and create a pull request. What do you think? Thank you for developing gtk-fortran.

**Comment by vmagnin** [comment]
Thanks for the kind words.

Yes, until GTK4 arrived, GTK was using Cairo for most renderings. In GTK4, it is still present but most renderings are now done with GL or Vulkan: https://developer.gnome.org/gtk4/stable/ch03s06.html

As you talk both about a separate fpm package and a pull request, I am not sure to understand exactly what you mean: 
- If you want to create a new repository with an fpm Cairo package based on gtk-fortran files (in fact all Cairo Fortran interfaces are in one file: `src/cairo-auto.f90`), feel free to do it following the terms of the GPLv3 license.
- If you mean creating a kind of sub-package inside gtk-fortran, I don't see exactly what it implies.

**Comment by ghost** [comment]
Hi @vmagnin . Thank you for the reply.

The original message is confusing, indeed. What I had in mind was something like this:

1. an (empty) repository would be created at https://github.com/vmagnin/fortran-cairo
2. I would clone (1), add `src/cairo-auto.f90`, `fpm.toml` manifest file, GPLv3-LICENSE file, etc
3. Create a pull request to (1)

If you agree, I can do (2) and (3).

**Comment by vmagnin** [comment]
@brocolis 
I could create the repository and give you direct access as a collaborator. It would be easier than managing pull requests. Or you could just create your own repository. It's OK for me, let me know what you prefer.

Should we call it `fortran-cairo` or `cairo-fortran` (like gtk-fortran)?

Note also that I think the version in the gtk4 branch may be newer that in the gtk3 branch, although I am not sure. In Fedora 33, the version is 1.16.0 (released in Oct. 2018: https://www.cairographics.org/news/).

**Comment by ghost** [comment]
Hi @vmagnin, I think I'll create my own repository and follow the name convention of the origin project, `cairo-fortran`, thanks for the permission 👍.

**Comment by vmagnin** [comment]
Let me know of your progress and I will add a link to your repo for people who could be interested only by Cairo.

**Comment by ghost** [comment]
@vmagnin, Hi, I started the project at https://github.com/brocolis/cairo-fortran 👍.

**Comment by vmagnin** [comment]
@brocolis 
Cool! I have just cloned it and build it without problem with fpm.
Note that as the Clarendon font is not installed on my machine, I have obtained a sans-serif F.

**Comment by vmagnin** [comment]
cairo-fortran is now appearing in:

- https://github.com/vmagnin/gtk-fortran/wiki/Projects-using-gtk-fortran
- https://github.com/vmagnin/gtk-fortran/wiki#news
