### ISSUE TITLE
Non-standard references to g_application_run

### ISSUE THREAD

**Issue by vansnyder** [vmagnin/gtk-fortran#255]
### Discussed in https://github.com/vmagnin/gtk-fortran/discussions/254

<div type='discussions-op-text'>

<sup>Originally posted by **vansnyder** March  8, 2022</sup>
The third argument of the subroutine g_application_run in module g is an array.

The subroutine is referenced twice, at line 86 in gtk-fortran.f90 and line 123 in gtk-hl-container.f90, with a scalar as the third argument.

gfortran apparently doesn't care about this mistake, but nagfor issues an error message and does not produce a .o file.

In both cases, c_null_ptr should be [c_null_ptr].
</div>

**Comment by vansnyder** [comment]
g_application_run is also referenced in the examples with a scalar for the third argument.

An alternative repair is to provide a generic g_application_run interface with two specific procedures, one with a scalar argv argument, and one with an array argv argument in the module g.

interface g_application_run

! GLIB_AVAILABLE_IN_ALL
!int g_application_run (GApplication *application, int argc, char **argv);
function g_application_run_array(application, argc, argv) bind(c)
  import :: c_int, c_ptr
  integer(c_int) :: g_application_run
  type(c_ptr), value :: application
  integer(c_int), value :: argc
  type(c_ptr), dimension(*) :: argv
end function

! GLIB_AVAILABLE_IN_ALL
!int g_application_run (GApplication *application, int argc, char **argv);
function g_application_run_array_scalar(application, argc, argv) bind(c)
  import :: c_int, c_ptr
  integer(c_int) :: g_application_run
  type(c_ptr), value :: application
  integer(c_int), value :: argc
  type(c_ptr), value :: argv
end function

end interface g_application_run

**Comment by vmagnin** [comment]
Thanks for reporting with nagfor. It is very interesting to use several compilers. I have only access to gfortran, ifort and ifx, which accept the following line:
```fortran
status = g_application_run(app, 0_c_int, c_null_ptr)
```
It could lead to interesting discussions, as in C `char **argv` is related to an array of strings.

I have successfully test the following line with gfortran, ifort and ifx: 
```fortran
status = g_application_run(app, 0_c_int, [c_null_ptr])
```
I will have to use it in the files you cited and in most of the examples.

This is indeed coherent with the interface defined in `glib-auto.f90`:
```fortran
! GLIB_AVAILABLE_IN_ALL
!int g_application_run (GApplication *application, int argc, char **argv);
function g_application_run(application, argc, argv) bind(c)
  import :: c_int, c_ptr
  integer(c_int) :: g_application_run
  type(c_ptr), value :: application
  integer(c_int), value :: argc
  type(c_ptr), dimension(*) :: argv
end function
```

**Comment by vmagnin** [comment]
I have pushed the fix in my development branch `gtk4-vmagnin`: could you try to compile it with nagfor?

**Comment by vmagnin** [comment]
I have merged the `gtk4-vmagnin` dev branch into `gtk4`.
I have also pushed the `g_application_run(app, 0_c_int, [c_null_ptr])` lines into the gtk3 branch.
