### ISSUE TITLE
add topic gtk-fortran

### ISSUE THREAD

**Issue by Beliavsky** [vmagnin/gtk-fortran#275]
add topic gtk-fortran

**Comment by vmagnin** [comment]
Do you mean a "gtk-fortran" label in Issues?

**Comment by Beliavsky** [comment]
I am suggesting that `gtk-fortran` be added to the About section with the other tags

**Comment by vmagnin** [comment]
Ah, sorry :-). I had not think to put the gtk-fortran tag in gtk-fortran itself...
Done.
