### ISSUE TITLE
Problem with gtkbuilder2: "Could not find signal handler"

### ISSUE THREAD

**Issue by jtappin** [vmagnin/gtk-fortran#49]
There seems to be a problem with gtkbuilder2 on PC BSD 9.0 with both gtk2 and gtk3 (-old branches in each case as glib is at 2.28). Since it occurs with Gtk+2 as well as 3, I don't think it's an issue of the version for which the interface files were generated, and the versions do match in gtk2.

```
(gtkbuilder2:2931): Gtk-WARNING **: Could not find signal handler 'destroy'

(gtkbuilder2:2931): Gtk-WARNING **: Could not find signal handler 'delete_event'

(gtkbuilder2:2931): Gtk-WARNING **: Could not find signal handler 'destroy'

(gtkbuilder2:2931): Gtk-WARNING **: Could not find signal handler 'button2clicked'

(gtkbuilder2:2931): Gtk-WARNING **: Could not find signal handler 'hello'
```

**Comment by vmagnin** [comment]
The problem reappeared in the current master branch (GTK 2), when building with CMake. But not in the gtk3 branch.

And yes, it runs with:

    gtk-fortran/build$ gfortran ../examples/gtkbuilder2.f90 `pkg-config --cflags --libs gtk-2-fortran`

See:
https://developer.gnome.org/gtk3/stable/GtkBuilder.html#gtk-builder-connect-signals

**Comment by vmagnin** [comment]
But it seems to be linked to libgmodule:
```bash
$ lsof | grep gtkbuild
gtkbuilde 13368                          vmagnin  mem       REG               8,17      18328    1440313 /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.6000.0
```

**Comment by vmagnin** [comment]
The gtkbuilder.f90 is running OK because it uses its own `connect_signals()` subroutine.

**Comment by vmagnin** [comment]
gtkbuilder2.f90 is running OK with MSYS2 / Windows 7.

**Comment by vmagnin** [comment]
Under Linux, the problem can appear with gtkf-sketcher and gtkbuilder2, which both uses GtkBuilder, if you build without the -rdynamic option (or -Wl,--export-dynamic) which passes the --export-dynamic option to the linker:

`(gtkf-sketcher:12818): Gtk-WARNING **: 10:29:43.249: Could not find signal handler 'file_open'.  Did you compile with -rdynamic?`

https://stackoverflow.com/questions/36692315/what-exactly-does-rdynamic-do-and-when-exactly-is-it-needed

But under MSYS2, don't use the -rdynamic option. That is why we have in the CMakeLists.txt file the code:
```
    if (UNIX)
      set(CMAKE_EXE_LINKER_FLAGS
          "-rdynamic")
    endif()
```
