### ISSUE TITLE
Issue with parallel build systems

### ISSUE THREAD

**Issue by IanH0073** [vmagnin/gtk-fortran#79]
Working from the gtk3 branch, I notice a number of the example executables that are in the examples directory have modules with the same name.  I am suspicious (based on observation) that if these examples are compiled with a build system that builds in parallel that this will cause issues with the mod file generated by a compiler for one target conflicting with a mod file for another target.

My knowledge of cmake is limited, but if restricting things to a serialised build is otherwise undesirable, presumably splitting the source for each example into its own directory, or explicitly directing output for each example to its own directory, or renaming the conflicting modules in source for each example to something unique are workarounds.  Suggestions?

**Comment by vmagnin** [comment]
I close that issue because it is an old post, but don't hesitate to reopen if the problem persists.

**Comment by ChinouneMehdi** [comment]
The problem still exists, try to build with `make -j` and you will get many errors.

**Comment by vmagnin** [comment]
The problem could be due to the fact that the order needed to build the whole project is not respected when working in parallel mode.
We need to look in CMake documentation to see what can be done.

**Comment by vmagnin** [comment]
Following:
https://cmake.org/cmake/help/latest/manual/cmake.1.html#build-a-project

I tried `cmake --build -j .` which seems to be the same as `make -j`

Then tried: `cmake -D CMAKE_BUILD_TYPE=debug -D CMAKE_BUILD_PARALLEL_LEVEL=4 ..`
but obtained that message:
```
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_BUILD_PARALLEL_LEVEL
```

**Comment by zbeekman** [comment]
FYI, `CMAKE_BUILD_ARALLEL_LEVEL` should be set as an environment variable, not a CMake variable.

**Comment by vmagnin** [comment]
Thanks for the information. 

I have tested:
```bash
$ export CMAKE_BUILD_PARALLEL_LEVEL=4
$ cmake -D CMAKE_BUILD_TYPE=debug  ..
$ cmake --build .
```
which is equivalent to:
```bash
$ cmake -D CMAKE_BUILD_TYPE=debug  ..
$ make -j 4
```

Note that the CMAKE_BUILD_PARALLEL_LEVEL variable has an effect only if you use `cmake --build .`, not with `make`.

**Comment by zbeekman** [comment]
Yes,
that is the expected/intended behavior, AFAICT.
